# Generated by Django 3.1.4 on 2021-09-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='image',
            field=models.ImageField(null=True, upload_to='comment_image'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
