# Generated by Django 3.1.4 on 2021-09-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210929_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='create_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
