# Generated by Django 3.1.4 on 2021-09-29 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210929_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplayBlogComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('mobile', models.CharField(blank=True, max_length=25)),
                ('website', models.URLField(blank=True)),
                ('image', models.ImageField(null=True, upload_to='comment_image')),
                ('message', models.TextField()),
                ('create_at', models.DateTimeField(auto_now=True, null=True)),
                ('update_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replay_blog', to='blog.blogcomment')),
            ],
        ),
    ]
