# Generated by Django 3.1.4 on 2021-10-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210930_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_name', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
