# Generated by Django 3.1.4 on 2021-10-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20211001_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipstore',
            name='ip_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
