# Generated by Django 3.1.4 on 2021-10-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_ipstore_ip_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='like',
            field=models.ManyToManyField(related_name='like', to='blog.IpStore'),
        ),
    ]
