# Generated by Django 3.1.4 on 2021-10-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blogpost_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='like',
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='like',
            field=models.ManyToManyField(related_name='like', to='blog.IpStore'),
        ),
    ]
