# Generated by Django 3.1.4 on 2021-10-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20211001_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='total_like',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
