# Generated by Django 3.1.2 on 2021-11-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20211103_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
