# Generated by Django 3.1.2 on 2021-11-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20211104_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='watching_time',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
